{
 "title": "Story Nodes Validators",
 "description": "This exporter is for monitoring information which is not provided from Tendermint’s basic Prometheus exporter (localhost:26660), and other specific information monitoring purposes",
 "time": { "from": "2024-10-08T05:50:07.260Z", "to": "2024-10-08T11:51:42.695Z" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "select the datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "======== Story Protocol Dashboard ========",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "<img style=\"display: block;-webkit-user-select: none;margin: auto;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;\" src=\"https://i.ytimg.com/vi/RQrfaIQ3ECg/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&amp;rs=AOn4CLCiWHwq6dSPC5W2zX0pCV8L7_bcaw\">"
   },
   "targets": [
    {
     "expr": "Cosmos_labels{instance=\"localhost:26660\"}\t",
     "legendFormat": "{{chainId}}"
    }
   ]
  },
  {
   "title": "Latest Block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{chain_id=\"iliad-0\",instance=\"localhost:26660\"}",
     "legendFormat": "Latest Block"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 13, "w": 9, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{chain_id=\"iliad-0\"}",
     "legendFormat": "Validator Count"
    }
   ]
  },
  {
   "title": "[ a node is block syncing ]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_blocksync_syncing{chain_id=\"iliad-0\"}",
     "legendFormat": "jailStatus"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_sum{chain_id=\"iliad-0\"}/cometbft_consensus_block_interval_seconds_count{chain_id=\"iliad-0\"}",
     "legendFormat": "Block Time"
    }
   ]
  },
  {
   "title": "[ Block Interval Times ]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(cometbft_consensus_block_interval_seconds_bucket{chain_id=\"iliad-0\"}[5m])) by (le))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "[Timing for each ABCI method]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(cometbft_abci_connection_method_timing_seconds_bucket{chain_id=\"iliad-0\"}[5m])) by (le, method))\n",
     "legendFormat": "{{Method}}"
    }
   ]
  },
  {
   "title": "[ Token Info ]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cosmos_minted_tokens{module=\"mint\"} ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "TXT Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(cosmos_tx_count[5m])) ",
     "legendFormat": "Transaction"
    },
    {
     "expr": "sum(rate(cosmos_tx_successful [5m])) ",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Receive Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(device) (irate(node_network_receive_bytes_total[1m]) * 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}